name: CI for Book Recommendation System

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # match your project’s version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest on notebooks
        run: |
          pip install nbconvert pytest
          pytest --maxfail=1 --disable-warnings -q

      - name: Run Streamlit app smoke test
        run: |
          pip install streamlit
          streamlit hello --headless --runOnSave false &
          sleep 10
          curl --fail http://localhost:8501 || exit 1

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install lint dependencies
        run: pip install flake8 black

      - name: Run linting
        run: |
          black --check .
          flake8 .
